services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    platform: linux/x86_64
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sidekiq-test/
    ports:
      - 3000:3000
    depends_on:
      - db

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

volumes:
  mysql_data:
